services:
  php:
    build:
      context: ./docker/php
    container_name: php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - node

  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  node:
    image: node:20-alpine
    container_name: node
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm ci && npm run dev"
    environment:
      VITE_API_URL: "http://localhost/api"
    expose:
      - "3000"
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025" 

volumes:
  db_data: